// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4Xo3X5xY4CsyvaPydpDvvc
// Component: zyq9GsFp2_
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_copy_of_minitwitter.module.css"; // plasmic-import: 4Xo3X5xY4CsyvaPydpDvvc/projectcss
import sty from "./PlasmicDelBtn.module.css"; // plasmic-import: zyq9GsFp2_/css

export const PlasmicDelBtn__VariantProps = new Array();

export const PlasmicDelBtn__ArgProps = new Array();

function PlasmicDelBtn__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {""}
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDelBtn__ArgProps,
          internalVariantPropNames: PlasmicDelBtn__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicDelBtn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDelBtn";
  } else {
    func.displayName = `PlasmicDelBtn.${nodeName}`;
  }
  return func;
}

export const PlasmicDelBtn = Object.assign(
  // Top-level PlasmicDelBtn renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicDelBtn
    internalVariantProps: PlasmicDelBtn__VariantProps,
    internalArgProps: PlasmicDelBtn__ArgProps
  }
);

export default PlasmicDelBtn;
/* prettier-ignore-end */
